name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: etgt
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        ecr: default
        logout: true
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        # Generate SBOM attestation for the build (shorthand for --attest=type=sbom)
        sbom: # optional
        # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        secrets: # optional
        # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
        secret-files: # optional
        # Size of /dev/shm (e.g., 2g)
        shm-size: # optional
        # List of SSH agent socket or keys to expose to the build
        ssh: # optional
        # List of tags
        tags: # optional
        # Sets the target stage to build
        target: # optional
        # Ulimit options (e.g., nofile=1024:1024)
        ulimit: # optional
        # GitHub Token used to authenticate against a repository for Git context
        github-token: # optional, default is ${{ github.token }}

        
    
    
