name: Entrega continua em Containers

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credencials
        uses: aws-actions/configure-aws-credencials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Arquivo da Tarefa 
        run: aws ecs describe-task-definition --task-definition  Tarefa_API-GO --query taskDefinition > task-definition.json

