name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.20', '1.19', '>=1.20']

    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: etgt
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        ecr: default
        logout: true
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: etgt/apredenco:${{ github.ref_name}}
